---
# Ansible Galaxy Collections Requirements
# Install with: ansible-galaxy collection install -r requirements.yml

collections:
    - name: community.general
      version: '>=8.0.0'
    - name: community.mysql
      version: '>=3.8.0'
    - name: ansible.posix
      version: '>=1.5.0'
