---
# roles/database/vars/main.yml
# NOTE: Sensitive variables should be stored in ansible-vault encrypted files
# See group_vars/all/vault.yml.example for vault usage

database_name: '{{ database_name }}'
database_user: '{{ database_user }}'
# SECURITY: Store passwords in vault.yml, not here
# database_password: "{{ vault_database_password }}"
# database_root_password: "{{ vault_database_root_password }}"
database_max_connections: 150
database_max_allowed_packet: '64M'
database_innodb_buffer_pool_size: '256M'
database_innodb_log_file_size: '64M'
